#! /bin/bash

if ifclass GERMAN; then
    $ROOTCMD locale-gen    LANG=de_DE.UTF-8
    $ROOTCMD update-locale LANG=de_DE.UTF-8
else
    ainsl -v /etc/locale.gen '^en_US.UTF-8 UTF-8'
    $ROOTCMD locale-gen
    $ROOTCMD update-locale LANG=en_US.UTF-8
fi

# check if we already use an external mirror
grep -q "external mirror" $target/etc/apt/sources.list && exit 0

cat <<EOM > $target/etc/apt/sources.list
# external mirror
deb $ubuntumirror/ubuntu $ubuntudist main restricted universe multiverse
deb $ubuntumirror/ubuntu $ubuntudist-updates main restricted universe multiverse
deb $ubuntumirror/ubuntu $ubuntudist-security main restricted universe multiverse
EOM
