#! /bin/bash

# (c) Michael Goetze, 2010-2011, mgoetze@mgoetze.net
# (c) Thomas Lange, 2011, Uni Koeln

error=0; trap 'error=$(($?>$error?$?:$error))' ERR # save maximum error code

ainsl -v /etc/fstab "proc	/proc	proc	defaults	0 0"
ainsl -v /etc/fstab "sysfs	/sys	sysfs	auto		0 0"

version=$($ROOTCMD rpm -qv kernel | cut -d- -f2-)


if [ -f $target/etc/lvm/lvm.conf ]; then
     sed -i -e 's/use_lvmetad = 1/use_lvmetad = 0/' $target/etc/lvm/lvm.conf
     ainsl -av /etc/dracut.conf.d/fai.conf 'add_dracutmodules+=" lvm "'
fi


# add filesystem driver into initrd
ainsl -av /etc/dracut.conf.d/fai.conf 'filesystems+="ext4"'
$ROOTCMD dracut -v --kver $version --force


exit $error
