#! /bin/bash

error=0; trap 'error=$(($?>$error?$?:$error))' ERR # save maximum error code

# set root password
if [ -n "$ROOTPW" ]; then
    $ROOTCMD chpasswd --encrypted <<< "root:${ROOTPW}"
elif [ -n "$username" ]; then
    $ROOTCMD usermod -L root
    # enable sudo for user
    $ROOTCMD usermod -aG sudo $username
    if [ ! -f $target/usr/bin/sudo ]; then
	echo "WARNING. Package sudo is not installed"
    fi
fi

exit $error
