#! /bin/bash

error=0; trap 'error=$(($?>$error?$?:$error))' ERR # save maximum error code

# set root password
if [ -n "$ROOTPW" ]; then
    $ROOTCMD chpasswd --encrypted <<< "root:${ROOTPW}"
elif [ -n "$username" ]; then
    $ROOTCMD usermod -L root
    # enable sudo for user
    ainsl /etc/sudoers "$username   ALL = ALL"
fi

exit $error
