#!/usr/bin/env bash
set -e

if [[ -n "${ROOTPW}" ]]; then
	$ROOTCMD chpasswd --encrypted <<< "root:${ROOTPW}"
elif [[ -n "${username}" ]]; then
    $ROOTCMD usermod -L root
    # enable sudo for user
    ainsl /etc/sudoers "$username   ALL = ALL"
fi
