#!/usr/bin/env bash

target="${target:?}";

### For good measure, make sure it's up and running ports 22,68
if $ROOTCMD which ufw 1>/dev/null 2>&1; then
  ### Make sure UFW is running upon reboot
  mkdir -p "${target}/etc/ufw/";
  ainsl -a /etc/ufw/ufw.conf "ENABLED=yes";
  ainsl -a /etc/ufw/ufw.conf "LOGLEVEL=low";

  $ROOTCMD ufw enable;
  $ROOTCMD ufw allow from any to any port 22 proto tcp;
  $ROOTCMD ufw allow from any to any port 68 proto udp;
else
  ### No ufw installed, just call iptables for help, again.
  if test -s "/etc/rc.local"; then
    ainsl -a "/etc/rc.local" "${FAI}/hooks/confdir.DEFAULT;";
  else
    ainsl -a "/etc/rc.local" "#!/usr/bin/env bash";
    ainsl -a "/etc/rc.local" "${FAI}/hooks/confdir.DEFAULT;";
    chmod 700 "${target}/etc/rc.local";
  fi;
  mkdir -p "${target}/${FAI}/hooks/";
  cp "${FAI}/hooks/confdir.DEFAULT" "${target}/${FAI}/hooks/confdir.DEFAULT";
fi;

### EOF
