#! /bin/bash

# (c) Michael Goetze, 2011, mgoetze@mgoetze.net
# (c) Thomas Lange 2014

error=0; trap 'error=$(($?>$error?$?:$error))' ERR # save maximum error code

if [ -r $LOGDIR/disk_var.sh ] ; then
	. $LOGDIR/disk_var.sh
else
	echo "disk_var.sh not found!"
	exit 1
fi


version=$($ROOTCMD rpm -qv kernel | cut -d- -f2-)

mount -o bind /dev $target/dev

    # CentOS 7
    $ROOTCMD grub2-install --no-floppy "$BOOT_DEVICE"
    $ROOTCMD grub2-mkconfig --output=/boot/grub2/grub.cfg

umount $target/dev

echo ""
echo "Grub installed on $BOOT_DEVICE = $bootdev"
echo "Grub boot partition is $BOOT_PARTITION = $bootpart"
echo "Root partition is $ROOT_PARTITION"
echo "Boot kernel: $version"

exit $error
