#! /bin/bash

# do only execute if this is called on the client being installed. Do not use during fai-diskimage
if [ X$FAI_ACTION = Xinstall ] && ! inside_nfsroot ; then
    exit 0
fi

# Echo architecture
command -v dpkg >&/dev/null && dpkg --print-architecture | tr a-z A-Z

# determin if we are a DHCP client or not
# count the : chars in the argument of ip=
n="${ip//[^:]}"
if [[ $ip =~ ^(on|any|dhcp)$ ]]; then
    echo DHCPC
elif [ ${#n} -lt 6 ]; then
    echo DHCPC
fi

exit 0
