#! /bin/bash

# assign classes to hosts based on their hostname

# do not use this if a menu will be presented
[ "$flag_menu" ] && exit 0

# use a list of classes for our demo machine
case $HOSTNAME in
    faiserver)
        echo "FAIBASE DEBIAN DEMO FAISERVER" ;;
    demohost|client*)
        echo "FAIBASE DEBIAN DEMO" ;;
    xfcehost)
        echo "FAIBASE DEBIAN DEMO XORG XFCE LVM";;
    gnomehost)
        echo "FAIBASE DEBIAN DEMO XORG GNOME";;
    ubuntuhost)
        echo "FAIBASE DEBIAN DEMO UBUNTU NOBLE NOBLE64 XORG";;
    rocky)
        echo "FAIBASE ROCKY"   # you may want to add class XORG here
        ifclass AMD64 && echo ROCKY9_64
	;;
    *)
        echo "FAIBASE DEBIAN DEMO" ;;
esac
