#! /bin/bash

# define classes for disk_config in an EFI enironment

if [ ! -d /sys/firmware/efi ] || ifclass GRUB_PC; then
    exit 0
fi

for c in LVM FAISERVER FAIBASE; do
    if ifclass $c; then
	echo ${c}_EFI
	break
    fi
done
